# Generated by Django 5.1 on 2024-09-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anote_ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anotacao',
            name='anotacao',
        ),
        migrations.RemoveField(
            model_name='anotacao',
            name='data',
        ),
        migrations.RemoveField(
            model_name='anotacao',
            name='status',
        ),
    ]
