# Generated by Django 5.1 on 2024-09-29 14:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anote_ai', '0002_remove_anotacao_anotacao_remove_anotacao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('done', 'Concluída')], default='todo', max_length=10),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
